all:
  children:
    frontend:
      hosts:
        kingsly-frontend:
          ansible_host: 44.200.212.23
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          instance_id: i-0cdd0e584ef66e8a1

    backend:
      hosts:
        kingsly-backend:
          ansible_host: 10.0.2.188
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ec2-user@44.200.212.23 -i ~/.ssh/id_rsa"'
          instance_id: i-010850738777fb332

    database:
      hosts:
        kingsly-database:
          ansible_host: 10.0.2.83
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ec2-user@44.200.212.23 -i ~/.ssh/id_rsa"'
          instance_id: i-0a84a7897990ff400

  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_hub_username: obenenoh2
    backend_private_ip: 10.0.2.188
    database_private_ip: 10.0.2.83
    frontend_public_ip: 44.200.212.23
